- tags:
    - install
  block:
    - name: Install package
      package:
        name: yggdrasil
        state: present

- tags:
    - configure
  block:
    - name: Read private key from existing config
      block:
        - slurp:
            src: "{{ yggdrasil_config_path }}"
          register: yggdrasil_existing_config
        - set_fact:
            yggdrasil_private_key: >-
              {{ yggdrasil_existing_config.content | b64decode |
                 regex_search('PrivateKey:\s*"?([0-9a-f]+)"?', '\1') | first }}
      when:
        - yggdrasil_manage_configuration
        - yggdrasil_private_key is not defined

    - name: Generate automatic configuration
      shell: yggdrasil -genconf > "{{ yggdrasil_config_path }}"
      args:
        creates: "{{ yggdrasil_config_path }}"
      when: yggdrasil_generate_configuration
      notify: restart yggdrasil

    - name: Generate configuration
      template:
        dest: "{{ yggdrasil_config_path }}"
        src: yggdrasil.conf.j2
        owner: yggdrasil
        group: yggdrasil
        mode: 0600
      when: yggdrasil_manage_configuration
      notify: restart yggdrasil

- name: Enable the service
  service:
    name: yggdrasil
    state: started
    enabled: yes
  tags:
    - service

- name: Check yggdrasil status
  command: yggdrasilctl getself
  register: ygg_output

- name: Get yggdrasil IPv6 address
  set_fact:
    yggdrasil_ipv6_address: "{{ ygg_output.stdout_lines | select('search', 'IPv6 address') | first | regex_replace('.*IPv6 address:\\s+([\\w:]+)', '\\1')| trim }}"
    yggdrasil_ipv6_subnet: "{{ ygg_output.stdout_lines | select('search', 'IPv6 subnet') | first | regex_replace('.*IPv6 subnet:\\s+([\\w:/]+)', '\\1')| trim }}"
